### ISSUE TITLE
Hey guys we have finally got the TimerBan API!

### ISSUE THREAD

**Issue by 64FF00** [DarkRealms/HardCorePvP#1]
https://github.com/onebone/TimerBan/commit/364badf846ccdb196440eff58571fe6b3bed0b39

Woohoo

**Comment by SavionLegendZzz** [comment]
hmmm so we can use the api now instead off using ConsoleCommand?

**Comment by xHFx** [comment]
but BalAnce pushed a new update on Main,php and it crashes the server..
